### ISSUE TITLE
Error running clean.sh

### ISSUE THREAD

**Issue by jhagberg** [NBISweden/mosler-micro-mosler#3]
jonas@knox1:~/mosler-micro-mosler$ ./clean.sh --all
You are not authorized to perform the requested action: identity:list_projects (HTTP 403) (Request-ID: req-906ab21e-acd1-42e0-8dc7-c291414b38ae)
Cleaning running machines

This is using the mmosler1 credential

**Comment by silverdaz** [comment]
Need to be an Openstack admin for it.
Should I check if you are in the script, and if you're not, exit with a message?

**Comment by silverdaz** [comment]
No answer. We'll pick up the matter when it appears anew.

**Comment by jhagberg** [comment]
Ye

**Comment by jhagberg** [comment]
Yes Either check if you are admin in the tenant or state it in the README perhaps you already have it there?

**Comment by silverdaz** [comment]
The README is now updated.
We can add those checks later, when the main functionality is in place
